### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by zehfernandes** [zehfernandes/gourmetstrike#1]
# Name Brainstorm.

Some ideas: 
- Gourmet Strike
- Gourpmet
- Gourappmet

**Comment by darthkurten** [comment]
I think that Gourmet Strike is a great name, but just to throw some names into the discussion:
#jesuisgourmet
Le gourmet
It's Gourmet Time!

**Comment by thiagogrossmann** [comment]
#Jesuisgorumet LOL

I rly liked Gourmet Strike, can't see problems.

**Comment by zehfernandes** [comment]
What you think a name that explain better what the site do: 
Elogio gourmet

or just the URL be www.elogiogourmet.com.br and the name still Gourmet Strike

@MuriloMafra Marketing guy what you say?

**Comment by darthkurten** [comment]
Wouldn't the user be confused by the difference between the name and URL?
