### ISSUE TITLE
Social Media images

### ISSUE THREAD

**Issue by zehfernandes** [zehfernandes/gourmetstrike#13]
Create an image to publish on social medias channels:
Illustration and logo.

Facebook width recommendation: 1200px

**Comment by darthkurten** [comment]
i can do this =D

**Comment by thiagogrossmann** [comment]
any of these?
![gourmet-strike---divulgacao-8](https://cloud.githubusercontent.com/assets/10821951/6401549/257cec7e-bde0-11e4-8550-84eab429d78b.png)
![gourmet-strike---divulgacao-1](https://cloud.githubusercontent.com/assets/10821951/6401550/2597f0b4-bde0-11e4-8478-f93fd074f33d.png)
![gourmet-strike---divulgacao-2](https://cloud.githubusercontent.com/assets/10821951/6401551/25ade004-bde0-11e4-85c0-afc88ef38d24.png)
![gourmet-strike---divulgacao-3-png](https://cloud.githubusercontent.com/assets/10821951/6401553/25b4a3c6-bde0-11e4-8cf8-274cbd3be494.png)
![gourmet-strike---divulgacao-4](https://cloud.githubusercontent.com/assets/10821951/6401552/25b41c80-bde0-11e4-80f8-d72aaba18dec.png)
![gourmet-strike---divulgacao-5](https://cloud.githubusercontent.com/assets/10821951/6401554/25b58c28-bde0-11e4-8bf5-5aed0c98bb5f.png)
![gourmet-strike---divulgacao-6](https://cloud.githubusercontent.com/assets/10821951/6401555/25b675e8-bde0-11e4-819b-b03cfd24ca10.png)
![gourmet-strike---divulgacao-7](https://cloud.githubusercontent.com/assets/10821951/6401556/25b67d86-bde0-11e4-8339-66f44cbaeea0.png)

**Comment by darthkurten** [comment]
I think that the first and the last are the best ones

2015-02-26 17:52 GMT-03:00 thiagogrossmann notifications@github.com:

> any of these?
> [image: gourmet-strike---divulgacao-8]
> https://cloud.githubusercontent.com/assets/10821951/6401549/257cec7e-bde0-11e4-8550-84eab429d78b.png
> [image: gourmet-strike---divulgacao-1]
> https://cloud.githubusercontent.com/assets/10821951/6401550/2597f0b4-bde0-11e4-8478-f93fd074f33d.png
> [image: gourmet-strike---divulgacao-2]
> https://cloud.githubusercontent.com/assets/10821951/6401551/25ade004-bde0-11e4-85c0-afc88ef38d24.png
> [image: gourmet-strike---divulgacao-3-png]
> https://cloud.githubusercontent.com/assets/10821951/6401553/25b4a3c6-bde0-11e4-8cf8-274cbd3be494.png
> [image: gourmet-strike---divulgacao-4]
> https://cloud.githubusercontent.com/assets/10821951/6401552/25b41c80-bde0-11e4-80f8-d72aaba18dec.png
> [image: gourmet-strike---divulgacao-5]
> https://cloud.githubusercontent.com/assets/10821951/6401554/25b58c28-bde0-11e4-8bf5-5aed0c98bb5f.png
> [image: gourmet-strike---divulgacao-6]
> https://cloud.githubusercontent.com/assets/10821951/6401555/25b675e8-bde0-11e4-819b-b03cfd24ca10.png
> [image: gourmet-strike---divulgacao-7]
> https://cloud.githubusercontent.com/assets/10821951/6401556/25b67d86-bde0-11e4-8339-66f44cbaeea0.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zehfernandes/gourmetstrike/issues/13#issuecomment-76270120
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by gui-santos** [comment]
My vote goes for the first one and the last one too!

_Guilherme Gonçalves Santos_

_behance.net/guilhermegs https://www.behance.net/guilhermegs_
guilherme.goncalvessantos@gmail.com
Fone: (41) 9945 8926
Skype: gui_gsantos

2015-02-26 17:59 GMT-03:00 Guilherme Kurten notifications@github.com:
