### ISSUE TITLE
Visual Style

### ISSUE THREAD

**Issue by zehfernandes** [zehfernandes/gourmetstrike#2]
The ideia is come across something like that.
Vector illustrations and shapes that simulate some organic movements with smooth border radius and angular lines. 

First screen like old game title screen:
![Visual style](https://dl.dropboxusercontent.com/u/8015936/gourmet/esboco.png)
_obs: placeholder illustration. Just Mockup_

Opinions?

**Comment by thiagogrossmann** [comment]
Yeah, the style is ok. If you want could be one illustration in 8 bit maybe?!
I liked the print marks in this example.

But what you want to be on the image? so i can make some sketches

**Comment by darthkurten** [comment]
Just for the fun of it i would let the people add a photo and the results would be displayed over it. (maybe with some integration with vsco cam haha)?

**Comment by zehfernandes** [comment]
Screen 2

![1](https://cloud.githubusercontent.com/assets/1891339/6306282/61a6b0b6-b919-11e4-9571-b1be5db57173.jpg)
