### ISSUE TITLE
Mechanic

### ISSUE THREAD

**Issue by zehfernandes** [zehfernandes/gourmetstrike#3]
The idea is simple generate randmoicalu food complains, using formulas:

```
(introdução de frase) + (adjetivo vazio) +  (modo operanti) + (sabor)
(unidade de metida) + (adjetivo ao chefe) + (ingrediente)
```

Pulling words of google drive spreadsheet for each category:
- adjetivo = delicioso, brilhante, genial, estupendo, criativo, maravilhoso
- introdução de frase = Nota-se, percebe-se, é possível sentir, é perceptível, fica claro, logo é aparente

Do you think could be interesting the app have the input of the name of the food?

**Comment by thiagogrossmann** [comment]
If you could input the name of the food, you will start one subdivision, like sweet or salty, could be interesting if you want to instant share one picture, with your complaint, for example.

**Comment by darthkurten** [comment]
I agree, i think that u should add (beside the name), couple of narrowing filters, maybe adding a dessert filter + sweet or salty. An "Key ingredient" selector would be nice. 

Example:
(name of the food) + (sweet or salty) + (key ingredient)
eg: brigadeiro + doce + chocolate

That way you could achieve more accurate results.
