### ISSUE TITLE
Illustration

### ISSUE THREAD

**Issue by zehfernandes** [zehfernandes/gourmetstrike#5]
The Grid

![Grid1](https://dl.dropboxusercontent.com/u/8015936/gourmet/1.png)

![Grid2](https://dl.dropboxusercontent.com/u/8015936/gourmet/2.png)

**Comment by gui-santos** [comment]
Nice!

**Comment by thiagogrossmann** [comment]
First sketch, what do you think?

![gs - 1](https://cloud.githubusercontent.com/assets/10821951/6097666/c8519fbc-afad-11e4-979b-eb416efbf95b.png)

**Comment by thiagogrossmann** [comment]
![Uploading GS - 2.png . . .]()

**Comment by thiagogrossmann** [comment]
![gs - 2](https://cloud.githubusercontent.com/assets/10821951/6097803/8216cb90-afb1-11e4-9e75-a2232858a91a.png)

**Comment by thiagogrossmann** [comment]
![gs - 3](https://cloud.githubusercontent.com/assets/10821951/6098047/652c1028-afb9-11e4-98b4-b79bb4b05f74.png)

**Comment by thiagogrossmann** [comment]
![gs - 4](https://cloud.githubusercontent.com/assets/10821951/6098344/abc8066e-afc2-11e4-9e4c-5eff0c2596cd.png)

**Comment by thiagogrossmann** [comment]
![gs - 5](https://cloud.githubusercontent.com/assets/10821951/6098528/aa24d764-afc8-11e4-8273-8e0a2daab13c.png)

**Comment by zehfernandes** [comment]
Awesome!!
