### ISSUE TITLE
UI Animations

### ISSUE THREAD

**Issue by gui-santos** [zehfernandes/gourmetstrike#6]
We need some UI Illustrations for the layout elements:
1. Logo;
2. Button "Gerar Elogio":
   2.1 Intro;
   2.2 Hover;
   2.3 Down;
3. Illustration;

**Comment by gui-santos** [comment]
I made a low-res video for you to preview what I planned for the UI intro

Download this:
https://www.dropbox.com/s/z5bq32bi8zsk1lb/gourmet_strike_anima.mp4?dl=0

I think the whole animation can be a little faster and the idle of the character smoother, but I will work on these things another time.

What do you think?

**Comment by gui-santos** [comment]
Ah! The whole screen blinking white for less than a second was me trying to emulate a "lightning". The intention was to illustrate the "strike" from "Gourmet STRIKE!"

**Comment by thiagogrossmann** [comment]
the logo seems a little bit different, it's ok?

**Comment by darthkurten** [comment]
I think that the logo transition from the horizontal to the skewed position
could be smoother, as if the words were falling (like a broken sign). What
do you guys think

2015-02-12 0:59 GMT-02:00 thiagogrossmann notifications@github.com:

> the logo seems a little bit different, it's ok?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zehfernandes/gourmetstrike/issues/6#issuecomment-74009577
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by gui-santos** [comment]
The logo is different beacause for the mock-up I just rotated it and not skewed it. It was just to guide me in the code so it doesn't need to be 100% like the end result.

I'm not sure I undestood the broken sign reference. Did you mean the words skewing down and slower?

**Comment by darthkurten** [comment]
Kinda,  i gess that  the two words should skew downwards when the lightning
strikes (and in a more smooth way), That way you could relate the two
actions in a more meaningful way.

2015-02-12 10:11 GMT-02:00 Guilherme Gonçalves notifications@github.com:

> The logo is different beacause for the mock-up I just rotated it and not
> skewed it. It was just to guide me in the code so it doesn't need to be
> 100% like the end result.
> 
> I'm not sure I undestood the broken sign reference. Did you mean the words
> skewing down and slower?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zehfernandes/gourmetstrike/issues/6#issuecomment-74061244
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by darthkurten** [comment]
I don't know, but i think the illustration takes up much of the attention,
cluttering the interface, maybe Thiago could use only magenta shades to
create the character, that way it would be more of a background, not the
central element of the design. What do you guys think?

2015-02-12 10:15 GMT-02:00 Guilherme Kurten guilherme.krten@gmail.com:

> Kinda,  i gess that  the two words should skew downwards when the
> lightning strikes (and in a more smooth way), That way you could relate the
> two actions in a more meaningful way.
> 
> 2015-02-12 10:11 GMT-02:00 Guilherme Gonçalves notifications@github.com:
> 
> > The logo is different beacause for the mock-up I just rotated it and not
> > skewed it. It was just to guide me in the code so it doesn't need to be
> > 100% like the end result.
> > 
> > I'm not sure I undestood the broken sign reference. Did you mean the
> > words skewing down and slower?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/zehfernandes/gourmetstrike/issues/6#issuecomment-74061244
> > .
> 
> ## 
> 
> Guilherme Kürten
> Designer Gráfico
> 
> Portfolio: behance.net/kurten http://www.behance.net/kurten
> 
> Telefone: (41) 84000588
> facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by gui-santos** [comment]
GOT IT! I'll give it a try. I think a little adjustment in the timing will do it.

But the overall action is cool then?

**Comment by darthkurten** [comment]
I like it, but idk what Zé thinks, maybe he has different thoughts about
how it should work

2015-02-12 10:21 GMT-02:00 Guilherme Gonçalves notifications@github.com:

> GOT IT! I'll give it a try. I think a little adjustment in the timing will
> do it.
> 
> But the overall action is cool then?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zehfernandes/gourmetstrike/issues/6#issuecomment-74062247
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by zehfernandes** [comment]
I like the mockup for to reasons:
- Simple animations easy to do with CSS. What it's great!
- The idea of strike!

My suggestion is the logo appear more like this:
http://codepen.io/zehfernandes/pen/myXbyR

But remember it's your ui animations. Do whatever you want :)

_PS: I agree with you darthkurten about the illustration calling so much attention. But the interface have just one button. Maybe this is not a problem._

**Comment by darthkurten** [comment]
I think that the logo could appear like Zé told, but in a horizontal
fashion, then the lightning comes and skew the words (too much?)

2015-02-12 11:47 GMT-02:00 Zeh Fernandes notifications@github.com:

> I like the mockup for to reasons:
> - Simple animations easy to do with CSS. What it's great!
> - The idea of strike!
> 
> My suggestion is the logo appear more like this:
> http://codepen.io/zehfernandes/pen/myXbyR
> 
> But remember it's your ui animations. Do whatever you want :)
> 
> _PS: I agree with you darthkurten about the illustration calling so much
> attention. But the interface have just one button. Maybe this is not a
> problem._
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zehfernandes/gourmetstrike/issues/6#issuecomment-74072490
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by thiagogrossmann** [comment]
if you want i can change the illustration.

here my considerations, but you know im a stupid:
- reduce illustration
- movement the logo from the right and left
- enlarge de button

![01](https://cloud.githubusercontent.com/assets/10821951/6172085/d78da8d4-b2c5-11e4-9f41-f1e936bb78a5.png)

And other thing, that flash light, there is any way to make something like this (sorry about my representation)

![02](https://cloud.githubusercontent.com/assets/10821951/6172190/51c3bb84-b2c6-11e4-892f-5d07cf87e579.png)

![03](https://cloud.githubusercontent.com/assets/10821951/6172193/54fd7d3a-b2c6-11e4-889e-e7852ed5fb6e.png)

**Comment by thiagogrossmann** [comment]
hehe sorry

**Comment by darthkurten** [comment]
i think that the 60's-batman-style splash would be too much, but I don't
know

2015-02-12 15:10 GMT-02:00 Guilherme Gonçalves notifications@github.com:

> Reopened #6 https://github.com/zehfernandes/gourmetstrike/issues/6.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zehfernandes/gourmetstrike/issues/6#event-234819574.

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by gui-santos** [comment]
Actually Thiago, the logo coming from the sides of the screen is something I'm going to try tonight!

I also agree with you about the logo size. It can be bigger but not that big.

And I think that your explosion is a lot more believable than my "lightning". But I don't know if I can make a cool effect without using sprites, but I will try for sure!

**Comment by thiagogrossmann** [comment]
the style i think is something like this

https://www.youtube.com/watch?v=ddmTtfUDNiE#t=432

lol

**Comment by gui-santos** [comment]
GOT IT!

Btw... Guacamelee is a fucking great PS3 game!
